# Bot ID
# Add the Client ID of bot which should be running Bastion.
# https://discord.com/developers/applications
# `TESSERACT_BOT_ID` environment variable overwrites this value.
id: ""

# Bot Token
# Add the token of the bot which should be running Bastion.
# https://discord.com/developers/applications
# `TESSERACT_BOT_TOKEN` environment variable overwrites this value.
token: ""

# Bot Owners
# User IDs of users who should be considered as the bot owners.
# `TESSERACT_OWNER_ID` environment variable adds an additional owner to the list.
owners:
  - "YOUR_USER_ID"
  - "ANOTHER_USER_ID"

# MongoDB connection URI
# `TESSERACT_MONGO_URI` environment variable overwrites this value.
mongoURI: "mongodb://127.0.0.1:27017/bastion"

# Presences
# Bastion will cycle through these activities randomly.
# status — online / idle / dnd / invisible
# activity — 0 (Playing) / 1 (Streaming) / 2 (Listening) / 3 (Watching) / 5 (Competing)
# name — string
# url — Twitch URL when `activity` is set to
presences:
- status: "online"
  activity: 3
  name: "the server"
  url:
- status: "dnd"
  activity: 1
  name: "some games"
  url: https://twitch.tv/iamtraction

# Enable Music Activity
# When enabled, Bastion updates the activity to the currently playing track.
# It should ideally be disabled if music is played on multiple servers.
# `BASTION_MUSIC_ACTIVITY` environment variable overwrites this value.
musicActivity: true

# Relay Direct Messages
# When enabled, Bastion will relay any direct messages it receives to the
# owner of the bot application / team.
# If a Discord webhook URL is specified, it'll relay the direct messages
# via the webhook.
# `BASTION_RELAY_DMS` environment variable overwrites this value.
relayDirectMessages: false

# Safe Mode
# When enabled, this disables usage of unsafe commands like `exec` and `eval`.
# Keep this enabled if the bot owner isn't exclusively you.
# `TESSERACT_UNSAFE_MODE` environment variable overwrites this value.
unsafeMode: false

# Bastion API Port
# Port used for Bastion API Server.
# If port isn't set the API server won't start.
# `BASTION_API_PORT` and `PORT` environment variables overwrites this value.
port: 8377

# Bastion API Auth
# Auth for accessing the Bastion API Server.
# If auth isn't set the API server won't start.
# `BASTION_API_AUTH` environment variable overwrites this value.
auth: ""

# API Keys
# These are optional and only required for specific features and/or commands.

# Required for `cryptocurrency` command.
coinMarketCapApiKey: ""
# Required for `apod` command.
nasaApiKey: "DEMO_KEY"
# Required for `weather` command.
openWeatherMapApiKey: ""
# Required for `movie` and `tv` commands.
tmdbApiKey: ""
# Required for `apex`, `csgo`, and `fortnite` commands.
trackerNetworkApiKey: ""
# Required for `game` command.
twitch:
  clientId: ""
  clientSecret: ""
  accessToken: ""
# Required for `rainbow6` command.
ubisoft:
  email: ""
  password: ""
# Required for `definitions` command.
wordnikApiKey: ""

# Additional Settings
# These settings are for internal use only. You don't need to configure this.
bastion:
  webhookId: ""
  webhookToken: ""
patreon:
  accessToken: ""
